# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
server:
  port: 8089

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: setting
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

ISSUER_ADDRESS: http://api-gateway:9001

ISSUER_URI: ${ISSUER_ADDRESS}/issuer
JWT_SET_URI: ${ISSUER_ADDRESS}/issuer/.well-known/jwks.json

spring:
  cloud:
    kubernetes:
      enabled: false

NEW_RELIC_ENABLED: false