logging:
  level:
    root: info
    me:
      sonam: debug

info:
  app:
    name: Setting rest service
    description: This application will provide a connection between two users
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

spring:
  application:
    name: setting-rest-service
  r2dbc:
      url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      properties:
        sslMode:  ${DB_SSLMODE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

user-rest-service:
  root: ${USER_REST_SERVICE}
  context: ${user-rest-service.root}/users

notification-rest-service:
  root: ${NOTIFICATION_REST_SERVICE}
  context: ${notification-rest-service.root}/notifications

permitpath:
  - path: /settings/health/*
    httpMethods: GET

requestFilters:


